# Generated by Django 6.0.4 on 2026-04-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MANAGER", "Manager"),
                    ("TL", "Team Lead"),
                    ("DEV", "Developer"),
                    ("TESTER", "Tester"),
                    ("DESIGNER", "Designer"),
                ],
                default="DEV",
                max_length=20,
            ),
        ),
    ]
