# Generated by Django 6.0.4 on 2026-04-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
        ("sprints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sprints",
                to="boards.board",
            ),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
