# Generated by Django 6.0.4 on 2026-04-17 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sprints", "0002_sprint_board_alter_sprint_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprint",
            name="completed_issues",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sprint",
            name="completed_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sprint",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sprint",
            name="goal",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sprint",
            name="issue_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sprint",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="sprint",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                ],
                default="PLANNED",
                max_length=20,
            ),
        ),
    ]
