# Generated by Django 6.0.4 on 2026-04-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "board_type",
                    models.CharField(
                        choices=[("SCRUM", "Scrum"), ("KANBAN", "Kanban")],
                        max_length=20,
                    ),
                ),
                (
                    "project_key",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("created_by", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
